# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/sis8300ku_bsp_system_xdma_0_0.xci
# IP: The module: 'sis8300ku_bsp_system_xdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_2/xdma_v4_1_6_blk_mem_64_noreg_be.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_v4_1_6_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_1_6_blk_mem_64_noreg_be} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_1/xdma_v4_1_6_blk_mem_64_reg_be.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_v4_1_6_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_1_6_blk_mem_64_reg_be} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_0/sis8300ku_bsp_system_xdma_0_0_pcie3_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sis8300ku_bsp_system_xdma_0_0_pcie3_ip || ORIG_REF_NAME==sis8300ku_bsp_system_xdma_0_0_pcie3_ip} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_0/ip_0/sis8300ku_bsp_system_xdma_0_0_pcie3_ip_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sis8300ku_bsp_system_xdma_0_0_pcie3_ip_gt || ORIG_REF_NAME==sis8300ku_bsp_system_xdma_0_0_pcie3_ip_gt} -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_2/xdma_v4_1_6_blk_mem_64_noreg_be_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_1/xdma_v4_1_6_blk_mem_64_reg_be_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_0/ip_0/synth/sis8300ku_bsp_system_xdma_0_0_pcie3_ip_gt_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_0/ip_0/synth/sis8300ku_bsp_system_xdma_0_0_pcie3_ip_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sis8300ku_bsp_system_xdma_0_0_pcie3_ip_gt || ORIG_REF_NAME==sis8300ku_bsp_system_xdma_0_0_pcie3_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_0/source/sis8300ku_bsp_system_xdma_0_0_pcie3_ip-PCIE_X0Y1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sis8300ku_bsp_system_xdma_0_0_pcie3_ip || ORIG_REF_NAME==sis8300ku_bsp_system_xdma_0_0_pcie3_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_0/synth/sis8300ku_bsp_system_xdma_0_0_pcie3_ip_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/sis8300ku_bsp_system_xdma_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sis8300ku_bsp_system_xdma_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/source/sis8300ku_bsp_system_xdma_0_0_pcie3_us_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'sis8300ku_bsp_system_xdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/synth/sis8300ku_bsp_system_xdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sis8300ku_bsp_system_xdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/sis8300ku_bsp_system_xdma_0_0.xci
# IP: The module: 'sis8300ku_bsp_system_xdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_2/xdma_v4_1_6_blk_mem_64_noreg_be.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_v4_1_6_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_1_6_blk_mem_64_noreg_be} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_1/xdma_v4_1_6_blk_mem_64_reg_be.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_v4_1_6_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_1_6_blk_mem_64_reg_be} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_0/sis8300ku_bsp_system_xdma_0_0_pcie3_ip.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sis8300ku_bsp_system_xdma_0_0_pcie3_ip || ORIG_REF_NAME==sis8300ku_bsp_system_xdma_0_0_pcie3_ip} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_0/ip_0/sis8300ku_bsp_system_xdma_0_0_pcie3_ip_gt.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sis8300ku_bsp_system_xdma_0_0_pcie3_ip_gt || ORIG_REF_NAME==sis8300ku_bsp_system_xdma_0_0_pcie3_ip_gt} -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_2/xdma_v4_1_6_blk_mem_64_noreg_be_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_1/xdma_v4_1_6_blk_mem_64_reg_be_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_0/ip_0/synth/sis8300ku_bsp_system_xdma_0_0_pcie3_ip_gt_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_0/ip_0/synth/sis8300ku_bsp_system_xdma_0_0_pcie3_ip_gt.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sis8300ku_bsp_system_xdma_0_0_pcie3_ip_gt || ORIG_REF_NAME==sis8300ku_bsp_system_xdma_0_0_pcie3_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_0/source/sis8300ku_bsp_system_xdma_0_0_pcie3_ip-PCIE_X0Y1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sis8300ku_bsp_system_xdma_0_0_pcie3_ip || ORIG_REF_NAME==sis8300ku_bsp_system_xdma_0_0_pcie3_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_0/synth/sis8300ku_bsp_system_xdma_0_0_pcie3_ip_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/sis8300ku_bsp_system_xdma_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sis8300ku_bsp_system_xdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/source/sis8300ku_bsp_system_xdma_0_0_pcie3_us_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'sis8300ku_bsp_system_xdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/synth/sis8300ku_bsp_system_xdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sis8300ku_bsp_system_xdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
