# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/sis8300ku_bsp_system_ddr4_0_0.xci
# IP: The module: 'sis8300ku_bsp_system_ddr4_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/ip_1/sis8300ku_bsp_system_ddr4_0_0_phy.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sis8300ku_bsp_system_ddr4_0_0_phy || ORIG_REF_NAME==sis8300ku_bsp_system_ddr4_0_0_phy} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/ip_0/sis8300ku_bsp_system_ddr4_0_0_microblaze_mcs.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sis8300ku_bsp_system_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==sis8300ku_bsp_system_ddr4_0_0_microblaze_mcs} -quiet] -quiet

# Block Designs: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/bd_2353.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353 || ORIG_REF_NAME==bd_2353} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_0/bd_2353_microblaze_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353_microblaze_I_0 || ORIG_REF_NAME==bd_2353_microblaze_I_0} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_1/bd_2353_rst_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353_rst_0_0 || ORIG_REF_NAME==bd_2353_rst_0_0} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_2/bd_2353_ilmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353_ilmb_0 || ORIG_REF_NAME==bd_2353_ilmb_0} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_3/bd_2353_dlmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353_dlmb_0 || ORIG_REF_NAME==bd_2353_dlmb_0} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_4/bd_2353_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353_dlmb_cntlr_0 || ORIG_REF_NAME==bd_2353_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_5/bd_2353_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353_ilmb_cntlr_0 || ORIG_REF_NAME==bd_2353_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_6/bd_2353_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353_lmb_bram_I_0 || ORIG_REF_NAME==bd_2353_lmb_bram_I_0} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_7/bd_2353_second_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_2353_second_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_8/bd_2353_second_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_2353_second_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_9/bd_2353_second_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_2353_second_lmb_bram_I_0} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_10/bd_2353_iomodule_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353_iomodule_0_0 || ORIG_REF_NAME==bd_2353_iomodule_0_0} -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/ip_1/par/sis8300ku_bsp_system_ddr4_0_0_phy_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_0/bd_2353_microblaze_I_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2353_microblaze_I_0 || ORIG_REF_NAME==bd_2353_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_0/bd_2353_microblaze_I_0_ooc_debug.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_1/bd_2353_rst_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2353_rst_0_0 || ORIG_REF_NAME==bd_2353_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_1/bd_2353_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2353_rst_0_0 || ORIG_REF_NAME==bd_2353_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_2/bd_2353_ilmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2353_ilmb_0 || ORIG_REF_NAME==bd_2353_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_3/bd_2353_dlmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2353_dlmb_0 || ORIG_REF_NAME==bd_2353_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_6/bd_2353_lmb_bram_I_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_9/bd_2353_second_lmb_bram_I_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_10/bd_2353_iomodule_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2353_iomodule_0_0 || ORIG_REF_NAME==bd_2353_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/bd_2353_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/ip_0/sis8300ku_bsp_system_ddr4_0_0_microblaze_mcs_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sis8300ku_bsp_system_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==sis8300ku_bsp_system_ddr4_0_0_microblaze_mcs} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/ip_0/sis8300ku_bsp_system_ddr4_0_0_microblaze_mcs_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/sis8300ku_bsp_system_ddr4_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sis8300ku_bsp_system_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/par/sis8300ku_bsp_system_ddr4_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sis8300ku_bsp_system_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/sis8300ku_bsp_system_ddr4_0_0.xci
# IP: The module: 'sis8300ku_bsp_system_ddr4_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/ip_1/sis8300ku_bsp_system_ddr4_0_0_phy.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sis8300ku_bsp_system_ddr4_0_0_phy || ORIG_REF_NAME==sis8300ku_bsp_system_ddr4_0_0_phy} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/ip_0/sis8300ku_bsp_system_ddr4_0_0_microblaze_mcs.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sis8300ku_bsp_system_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==sis8300ku_bsp_system_ddr4_0_0_microblaze_mcs} -quiet] -quiet

# Block Designs: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/bd_2353.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353 || ORIG_REF_NAME==bd_2353} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_0/bd_2353_microblaze_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353_microblaze_I_0 || ORIG_REF_NAME==bd_2353_microblaze_I_0} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_1/bd_2353_rst_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353_rst_0_0 || ORIG_REF_NAME==bd_2353_rst_0_0} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_2/bd_2353_ilmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353_ilmb_0 || ORIG_REF_NAME==bd_2353_ilmb_0} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_3/bd_2353_dlmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353_dlmb_0 || ORIG_REF_NAME==bd_2353_dlmb_0} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_4/bd_2353_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353_dlmb_cntlr_0 || ORIG_REF_NAME==bd_2353_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_5/bd_2353_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353_ilmb_cntlr_0 || ORIG_REF_NAME==bd_2353_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_6/bd_2353_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353_lmb_bram_I_0 || ORIG_REF_NAME==bd_2353_lmb_bram_I_0} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_7/bd_2353_second_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_2353_second_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_8/bd_2353_second_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_2353_second_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_9/bd_2353_second_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_2353_second_lmb_bram_I_0} -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_10/bd_2353_iomodule_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2353_iomodule_0_0 || ORIG_REF_NAME==bd_2353_iomodule_0_0} -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/ip_1/par/sis8300ku_bsp_system_ddr4_0_0_phy_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_0/bd_2353_microblaze_I_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2353_microblaze_I_0 || ORIG_REF_NAME==bd_2353_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_0/bd_2353_microblaze_I_0_ooc_debug.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_1/bd_2353_rst_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2353_rst_0_0 || ORIG_REF_NAME==bd_2353_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_1/bd_2353_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2353_rst_0_0 || ORIG_REF_NAME==bd_2353_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_2/bd_2353_ilmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2353_ilmb_0 || ORIG_REF_NAME==bd_2353_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_3/bd_2353_dlmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2353_dlmb_0 || ORIG_REF_NAME==bd_2353_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_6/bd_2353_lmb_bram_I_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_9/bd_2353_second_lmb_bram_I_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_10/bd_2353_iomodule_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2353_iomodule_0_0 || ORIG_REF_NAME==bd_2353_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/bd_2353_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/ip_0/sis8300ku_bsp_system_ddr4_0_0_microblaze_mcs_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sis8300ku_bsp_system_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==sis8300ku_bsp_system_ddr4_0_0_microblaze_mcs} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/ip_0/sis8300ku_bsp_system_ddr4_0_0_microblaze_mcs_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/sis8300ku_bsp_system_ddr4_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sis8300ku_bsp_system_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/par/sis8300ku_bsp_system_ddr4_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sis8300ku_bsp_system_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
