[#ch_fwk_doc]
= Documentation

FWK follows the __Documentation as Code__ approach.
This means the documentation is keep together with the code in the same repository.
Documentation is written with text-based files with defined syntax, like Markdown, ReSt, LaTex, AsciiDoc...

Documentation in the framework prefers *AsciiDoc* syntax documents.

== AsciiDoc

AsciiDoc is a lightweight and semantic markup language primarily designed for writing technical documentation link:https://docs.asciidoctor.org/asciidoc[^1^].

Asciidoctor is the main engine used for the processing 
AsciiDoc `.adoc` format is supported by default by GitLab and GitHub.

For more information please check the following links;

link:https://docs.asciidoctor.org/[AsciiDoc Format and AsciiDoctor Documentation]

AsciiDoc has support in editors: Vim, Emacs, Atom, VS Code. +

It can also have a live preview

link:https://docs.asciidoctor.org/asciidoctor/latest/tooling/#ides-and-text-editors[AsciiDoctor LivePreview]

Final documentation can be generated with tools like link:https://antora.org[Antora]

[NOTE]
Please note that not all AsciiDoc features are supported by GitLab and GitHub.

== Structure

Each module and each project should have its own documentation.
All the documentation files should be placed in the **doc/** folder.

FWK can automatically generate documentation.
`.pdf` can be generated with the asciidoctor-pdf
`html` static site can be generated with Antora.

**doc/main.adoc** is the main document which should be placed in each source module and project.
This is the file is used to generate PDF file or to be used to preview all documentation.
It should just include sources from Antora modules.

**doc/antora.yml** is the entry for Antora module. Check: link:https://docs.antora.org/antora/latest/component-title/[antora.yml]. +
For Antora directory structure please follow link:https://docs.antora.org/antora/latest/standard-directories/[Antora documentation].

[NOTE]
If there is no default doc structure in the project FWK will create it.

Default project documentation tree is presented below:

.Project and module doc tree
----
./doc/
├── antora.yml
├── main.adoc
├── modules
│   └── ROOT
│       ├── images
│       ├── nav.adoc
│       └── pages
│           └── index.adoc
----

== Generate

Documentation is generate for the whole project. It combines all the sub modules documentations.
To generate documentation use below commands

[source,shell]
----
$ make <cfg=cfgName> doc_adoc   <1>
$ make <cfg=cfgName> doc_pdf    <2>
$ make <cfg=cfgName> doc_antora <3>
----
<1> Generate adoc files using DesyRDL. This command should be run first if any adoc files generated by DESY RDL are required.
<2> Generate PDF documentation using project `./doc/main.adoc` file as the main input file.
<3> Generate Antora static site with the projct module `./doc/antora.yml` as the main site. It will also add all the sources modules used in project.

To run all of the above steps at ones just run:

[source,shell]
----
$ make <cfg=cfgName> doc
----

== Requirements

To be able to generate documenation there are required tools to be installed on the system.
The Tool Chain required to have <<Antora>> and <<AsciiDoctor>> installed.
Please check below instructions for each tool.

There are also ready docker images ready to be used.


[NOTE]
It is recommended to use docker images. Please check <<Docker>>.

=== Antora

To be able to generate static HTML documentation site, Antora tool is required.
Please follow installation instructions: link:https://docs.antora.org/antora/latest/install/install-antora/[Install Antora] or use docker image.

Extensions required:

* asciidoctor-kroki
* @antora/lunr-extension
* mathjax
* @djencks/asciidoctor-mathjax* 

=== AsciiDoctor

To be able to generate PDF documentation file, AsciiDoctor tool is required.
Please follow installation instructions: link:https://docs.asciidoctor.org/asciidoctor/latest/install/[Install AsciiDoctor]

Extensions required:

* asciidoctor-pdf
* asciidoctor-diagram
* asciidoctor-mathematical

=== Docker

Installation of Antora and AsciiDoctor with extinctions may sometimes become time consuming and problematic.
For easy of use and stable environment there are ready docker images.

If docker images are installed on system, FWK prefers to run documentation generation over docker.

If you have already docker installed. Just install images with two commands:

.Antora
----
docker pull fwfwk/doc-antora
----

.AsciiDoctor
----
docker pull fwfwk/doc-asciidoctor
----
