= Introduction
ifndef::imagesdir[:imagesdir: ../images]

The main purpose of the framework is to standardize FPGA firmware project structure and project build process.
This is a set of rules and procedures which helps in the firmware build or simulation processes.

Some main points about the FPGA firmware framework:

* decouple sources from vendor HDL tools (one configuration file can be used to crate project for various tools)
* provides command line flow and allows contiguous integration (CI) over Jenkins, GitlabCI ...
* base mainly on **Tcl** scripts, which are supported by most of the HDL tools
* follows an IP-based approach where each designed module can be wrapped into an IP-Core
* gives a possibility to integrate or share various IPs/modules within designs
* mange address space of the registers in the design

NOTE: The FPGA firmware framework is shortly called `*fwk*`

NOTE: The `*fwk*` git repository should be added as a submodule to the superproject,
which should consist of other sources components. However, this is not mandatory and it can work with no revision control environment.

== General Structure

In <<fig_fwk_general>> general block diagram of `fwk` idea is presented.

.General framework structure
[#fig_fwk_general]
image::fwk_general.svg[]
{empty}

[#ch_fwk_tools_supp]
== Supported vendor tools

The list of the vendor tools supported by `fwk` is given in the <<fwk_vendor_tools_tab>>.

[#fwk_vendor_tools_tab]
[%autowidth]
.Tools support
|===
| Tool Name        | Support               | Type

| Xilinx Vivado    | yes                   | Synthesis
| Xilinx ISE       | yes                   | Synthesis
| Xilinx PlanAhead | yes                   | Synthesis
| Xilinx Vitis     | initial (in progress) | Processor support
| Xilinx XSDK      | initial (in progress) | Processor support
| Xilinx Appguru   | yes                   | Processor support
| cocotb           | yes                   | Simulation
| GDHL             | yes                   | Simulation
| VHDL LS          | yes                   | Error check
| VHDL Tool        | yes                   | Syntax check
| MG ModelSim      | no (planned)          | Simulation
| Intel Quartus    | no (planned)          | Synthesis
|===

[#ch_fwk_lib_supp]
== Supported libraries

The list of the external libraries supported by `fwk` is given in the <<fwk_ext_lib_tab>>.

[#fwk_ext_lib_tab]
[%autowidth]
.Libraries support
|===
| Library Name  | Support               | Type     | Reference

| OSVVM         | yes                   | HDL, Tcl | xref:ext_lib_osvvm.adoc[]
|===

[#ch_fwk_requirements]
== Requirements

`fwk` requires a number of tools to be installed on the system.

`fwk` is OS independed, it can run on Linux or Windows. Depends more on the vendor tool.

.Mandatory
* *GNU Make*
* *Tcl*

NOTE: On Windows `make` is shipped with Xilinx Vitis, `tcl` is shipped with Xilinx Vivado as `xtclsh`

.Optional
* *CMake* - used by GHDL backend
* *python 3* - needed for address map generation using desyrdl
** *python3 pip*
** *python3 venv*
* *desyrdl* - address space (VHDL,map,h,..) generation from the SystemRDL files
* *gtkwave* - shows traces generated by cocotb and GHDL simulator backends
