= Procedure Reference

`parseVhdlConfigFile`::
  Description:::
    Parses a VHDL file with constant definitions and returns constant
    variables in indexed array.
    Supported VHDL types:

    * std_logic_vector
    ** hexadecimal format, e.g. X"abcdef01"
    ** binary format, e.g. "110100101"
    * integer
    * natural
    * real
    * string
  Parameters:::
    * *varName* - target array variable
    * *vhdlFile* - VHDL file path to parse constants from

`addSrcModule`::
  Description:::
    Creates a new namespace under the current namespace with name `ModuleName`
    and populates it according to `TclFile`
  Parameters:::
    * *ModuleName* - name of the new child namespace to create
    * *TclFile* - path of the Tcl file that describes the source module to add

`addSources`::
  Description:::
    Calls the tool-specific `::fwfwk::tool::addSources` with the provided list
    of arguments. Typically this is a list of source file paths and optionally
    a target file set, library or language variant
  Parameters:::
    * *args* - list of arguments to parse on to the tool-specific function

`addAddressSpace AddressSpace Identifier Type AddressInfo Arg {Config {}}`::
  Description:::
    Adds one or more entries to a Tcl array that describes the address space of
    a module or project
  Parameters:::
    * *Type* - this determines how fwk handles the other parameters.
    ** RDL|IBUS|IPX: add an address map node that is described by an additional file
       (e.g. a SystemRDL file) or a design entity (e.g. an IP core). *Arg* sets the
       file or entity name.
    ** TOP|INTERCONNECT: add an empty address map node that other nodes (e.g. RDL)
       can be added to, representing a bus interconnect structure in the design.
       A corresponding .rdl file will be generated by fwk.
       Only for INTERCONNECT, DesyRDL will also generate HDL code.
    ** ARRAY: add a sub address map as an instance to the address map. *Arg* is an
       array created by `addAddressSpace`.
    ** (PROJECT: used internally)
    * *AddressSpace* - name of a new or existing array to which this function adds
      information about each new address space node
    * *Identifier* - the name of the new address space node. For `Type == ARRAY`,
      this will be the _instance_ name of the instantiated address space node
      (array key 'Name'), leaving the _type_ name unchanged (array key 'Id'). For
      any other `Type` it becomes the _type_ name. For `Type == RDL` it must match
      the type name of the `addrmap` in the SystemRDL file.
    * *AddressInfo* - can be empty, or define the address, range and access channel
      of an address map node in the format `{channel address range}`, or `{channel
      address}`, or `{address range}`, or `{address}`, or some variations with `@`
      and `&` as separators in front of `address` and `range`, respectively
    * *Arg* - depending on the *Type*, either a file (`.rdl` for RDL, `.vhd` for
      IBUS) or a block design instance name (for IPX) or an address space array
      (for ARRAY), or an empty string for ARRAY
    * *Config* (optional) - an array of configuration paramters, e.g. parsed from a
      `pkg_config_modulename.vhd` file

