# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.runs/synth_1/bsp_sis8300ku_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcku040-ffva1156-1-c

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.cache/wt [current_project]
set_property parent.project_path /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -vhdl2008 -library xil_defaultlib {
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/mimo/hdl/active.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/hdl/app_mmcm_wrapper.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/dev4/hdl/pkg_app_config_conf_2.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/hdl/pkg_bsp_config_default.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/mimo/hdl/delayline.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/mimo/hdl/iq.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/mimo/hdl/pkg_b32.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/mimo/hdl/ilc16.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/mimo/hdl/mimo.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/timing/hdl/trigger_generation.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/timing/hdl/timing_top.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/daq/hdl/daq_mux.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/daq/hdl/burst_generator.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/daq/hdl/daq_to_axi.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/daq/hdl/daq_timestamps.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/daq/hdl/daq_timestamps_to_mem.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/daq/hdl/daq_top.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/dev4/hdl/app_top.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/hdl/bsp_mmcm_wrapper.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/hdl/pkg_sis8300ku_payload.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/dev4/hdl/sis8300ku_payload.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/imports/hdl/sis8300ku_bsp_system_wrapper.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/fpga_config_manager/hdl/fpga_spi_io_phy.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/fpga_config_manager/hdl/fpga_spi_programmer.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/fpga_config_manager/hdl/icap_wrapper.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/fpga_config_manager/hdl/icap_boot_fsm.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/fpga_config_manager/hdl/icap_handler.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/fpga_config_manager/hdl/frame_ecc_wrapper.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/fpga_config_manager/hdl/fpga_config_manager_top.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/hdl/sis8300ku_bsp_logic_top.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/rtm_dwc8vm1/hdl/i2c_subsys.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/rtm_dwc8vm1/hdl/rtm_dwc8vm1_top.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/hdl/bsp_sis8300ku_top.vhd
}
read_vhdl -vhdl2008 -library desy {
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/peripheral/i2c/ad5624_over_pca9535.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/common/pkg_common_types.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/common/pkg_common_numarray.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/peripheral/adc/ad9628.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/misc/clock/app_clk_ctrl.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/hdl/pkg_bsp_ifs_cfg.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/common/pkg_common_axi_cfg.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/common/pkg_common_axi.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/common/pkg_common_bsp_ifs.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/memory/ram/dual_port_memory.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/misc/trigger_delay.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/misc/trigger_divider.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/math/pkg_math_basic.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/memory/fifo/pkg_memory_fifo.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/memory/fifo/fifo_input.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/memory/fifo/fifo_dualclock_macro.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/memory/fifo/fifo_virtex.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/memory/fifo/fifo_dpram.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/memory/fifo/fifo_generic.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/memory/fifo/fifo_output.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/memory/fifo/fifo.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/bus/axi/axi4_buf_sch.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/bus/axi/axi4_buf.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/misc/arbiter/arbiter_round_robin.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/bus/axi/axi4_mux.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/misc/arbiter/arbiter_priority_synced.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/peripheral/spi/axi4_spi_3w.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/common/pkg_common_to_desyrdl.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/misc/clock/clock_freq.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/misc/xdma_irq_handler.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/peripheral/dac/max5878.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/peripheral/sn74lv8153.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/memory/fifo/fifo_ultrascale.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/peripheral/i2c/pca9535.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/peripheral/i2c/hmc624_over_pca9535.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/peripheral/i2c/hyt271.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/peripheral/i2c/i2c_controller.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/peripheral/i2c/i2c_control_arbiter.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/desy_vhdl/hdl/peripheral/i2c/ltc2493.vhd
}
read_vhdl -vhdl2008 -library desyrdl {
  /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.desyrdl/vhdl/desyrdl/pkg_desyrdl_common.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.desyrdl/vhdl/APP/pkg_app.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.desyrdl/vhdl/APP/app_decoder_axi4l.vhd.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.desyrdl/vhdl/APP/app.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.desyrdl/vhdl/RTM/pkg_rtm.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.desyrdl/vhdl/TIMING/pkg_timing.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.desyrdl/vhdl/TIMING/timing_decoder_axi4l.vhd.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.desyrdl/vhdl/TIMING/timing.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.desyrdl/vhdl/DAQ/pkg_daq.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.desyrdl/vhdl/DAQ/daq_decoder_axi4l.vhd.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.desyrdl/vhdl/DAQ/daq.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.desyrdl/vhdl/BSP/pkg_sis8300ku_bsp_logic.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.desyrdl/vhdl/BSP/sis8300ku_bsp_logic_decoder_axi4l.vhd.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.desyrdl/vhdl/BSP/sis8300ku_bsp_logic.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.desyrdl/vhdl/FCM/pkg_fpga_config_manager.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.desyrdl/vhdl/FCM/fpga_config_manager_decoder_axi4l.vhd.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.desyrdl/vhdl/FCM/fpga_config_manager.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.desyrdl/vhdl/RTM/rtm_decoder_axi4l.vhd.vhd
  /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.desyrdl/vhdl/RTM/rtm.vhd
}
add_files /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/sis8300ku_bsp_system.bd
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_2/xdma_v4_1_6_blk_mem_64_noreg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_1/xdma_v4_1_6_blk_mem_64_reg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_0/ip_0/synth/sis8300ku_bsp_system_xdma_0_0_pcie3_ip_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_0/ip_0/synth/sis8300ku_bsp_system_xdma_0_0_pcie3_ip_gt.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_0/source/sis8300ku_bsp_system_xdma_0_0_pcie3_ip-PCIE_X0Y1.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/ip_0/synth/sis8300ku_bsp_system_xdma_0_0_pcie3_ip_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/sis8300ku_bsp_system_xdma_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/source/sis8300ku_bsp_system_xdma_0_0_pcie3_us_ip.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/synth/sis8300ku_bsp_system_xdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_1/bd_6579_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_1/bd_6579_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_2/bd_6579_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_2/bd_6579_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_3/bd_6579_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_3/bd_6579_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_4/bd_6579_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_5/bd_6579_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_6/bd_6579_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_7/bd_6579_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_8/bd_6579_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_12/bd_6579_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_13/bd_6579_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_14/bd_6579_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_15/bd_6579_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_16/bd_6579_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_17/bd_6579_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_21/bd_6579_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_22/bd_6579_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_23/bd_6579_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_24/bd_6579_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_25/bd_6579_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_26/bd_6579_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_27/bd_6579_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_28/bd_6579_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_29/bd_6579_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_30/bd_6579_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_31/bd_6579_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_32/bd_6579_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_34/bd_6579_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_35/bd_6579_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_36/bd_6579_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_37/bd_6579_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_38/bd_6579_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/bd_0/ip/ip_39/bd_6579_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_1/bd_c7d2_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_1/bd_c7d2_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_2/bd_c7d2_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_3/bd_c7d2_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_4/bd_c7d2_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_5/bd_c7d2_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_6/bd_c7d2_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_10/bd_c7d2_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_11/bd_c7d2_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_12/bd_c7d2_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_13/bd_c7d2_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_14/bd_c7d2_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_15/bd_c7d2_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_16/bd_c7d2_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_17/bd_c7d2_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_18/bd_c7d2_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_19/bd_c7d2_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_20/bd_c7d2_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_21/bd_c7d2_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_23/bd_c7d2_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_24/bd_c7d2_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_25/bd_c7d2_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_26/bd_c7d2_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_27/bd_c7d2_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/bd_0/ip/ip_28/bd_c7d2_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_1/bd_9e20_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_1/bd_9e20_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_2/bd_9e20_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_2/bd_9e20_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_3/bd_9e20_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_3/bd_9e20_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_4/bd_9e20_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_5/bd_9e20_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_6/bd_9e20_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_7/bd_9e20_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_8/bd_9e20_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_12/bd_9e20_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_13/bd_9e20_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_14/bd_9e20_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_15/bd_9e20_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_16/bd_9e20_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_17/bd_9e20_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_21/bd_9e20_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_22/bd_9e20_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_23/bd_9e20_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_24/bd_9e20_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_25/bd_9e20_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_26/bd_9e20_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_27/bd_9e20_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_28/bd_9e20_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_29/bd_9e20_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_30/bd_9e20_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_31/bd_9e20_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_32/bd_9e20_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_sys_reset_0_0/sis8300ku_bsp_system_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_sys_reset_0_0/sis8300ku_bsp_system_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_sys_reset_0_0/sis8300ku_bsp_system_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/ip_1/par/sis8300ku_bsp_system_ddr4_0_0_phy_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_0/bd_2353_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_0/bd_2353_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_1/bd_2353_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_1/bd_2353_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_2/bd_2353_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_3/bd_2353_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_6/bd_2353_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_9/bd_2353_second_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_10/bd_2353_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/bd_2353_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/ip_0/sis8300ku_bsp_system_ddr4_0_0_microblaze_mcs_board.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/ip_0/sis8300ku_bsp_system_ddr4_0_0_microblaze_mcs_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/sis8300ku_bsp_system_ddr4_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/par/sis8300ku_bsp_system_ddr4_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/sis8300ku_bsp_system_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/bd_0/ip/ip_0/data/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/ip_0/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/sw/calibration_0/Debug/calibration_ddr.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/dev4/cstr/default_sis8300ku.xdc
set_property used_in_implementation false [get_files /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/dev4/cstr/default_sis8300ku.xdc]

read_xdc /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_clocks.xdc
set_property used_in_implementation false [get_files /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_clocks.xdc]

read_xdc /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_adc.xdc
set_property used_in_implementation false [get_files /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_adc.xdc]

read_xdc /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_dac.xdc
set_property used_in_implementation false [get_files /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_dac.xdc]

read_xdc /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_rtm.xdc
set_property used_in_implementation false [get_files /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_rtm.xdc]

read_xdc /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_misc.xdc
set_property used_in_implementation false [get_files /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_misc.xdc]

read_xdc /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_pcie.xdc
set_property used_in_implementation false [get_files /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_pcie.xdc]

read_xdc /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_ddr4.xdc
set_property used_in_implementation false [get_files /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_ddr4.xdc]

read_xdc /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/timing_adc_default.xdc
set_property used_in_implementation false [get_files /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/timing_adc_default.xdc]

read_xdc /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/timing_clocks.xdc
set_property used_in_implementation false [get_files /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/timing_clocks.xdc]

read_xdc /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/timing_dac.xdc
set_property used_in_implementation false [get_files /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/timing_dac.xdc]

read_xdc /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/false_paths.xdc
set_property used_in_implementation false [get_files /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/false_paths.xdc]

read_xdc /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/bitstream_config.xdc
set_property used_in_implementation false [get_files /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/bitstream_config.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top bsp_sis8300ku_top -part xcku040-ffva1156-1-c -assert
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef bsp_sis8300ku_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file bsp_sis8300ku_top_utilization_synth.rpt -pb bsp_sis8300ku_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
