# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/dev4/cstr/default_sis8300ku.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_clocks.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_adc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_dac.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_rtm.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_misc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_pcie.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_ddr4.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/timing_adc_default.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/timing_clocks.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/timing_dac.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/false_paths.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/bitstream_config.xdc

# Block Designs: bd/sis8300ku_bsp_system/sis8300ku_bsp_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sis8300ku_bsp_system || ORIG_REF_NAME==sis8300ku_bsp_system} -quiet] -quiet

# IP: bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/sis8300ku_bsp_system_xdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sis8300ku_bsp_system_xdma_0_0 || ORIG_REF_NAME==sis8300ku_bsp_system_xdma_0_0} -quiet] -quiet

# IP: bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_reg_0/sis8300ku_bsp_system_axi_interconnect_reg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sis8300ku_bsp_system_axi_interconnect_reg_0 || ORIG_REF_NAME==sis8300ku_bsp_system_axi_interconnect_reg_0} -quiet] -quiet

# IP: bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_dma_0/sis8300ku_bsp_system_axi_interconnect_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sis8300ku_bsp_system_axi_interconnect_dma_0 || ORIG_REF_NAME==sis8300ku_bsp_system_axi_interconnect_dma_0} -quiet] -quiet

# IP: bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/sis8300ku_bsp_system_axi_interconnect_ddr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sis8300ku_bsp_system_axi_interconnect_ddr_0 || ORIG_REF_NAME==sis8300ku_bsp_system_axi_interconnect_ddr_0} -quiet] -quiet

# IP: bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_sys_reset_0_0/sis8300ku_bsp_system_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sis8300ku_bsp_system_sys_reset_0_0 || ORIG_REF_NAME==sis8300ku_bsp_system_sys_reset_0_0} -quiet] -quiet

# IP: bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_ddr4_0_0/sis8300ku_bsp_system_ddr4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sis8300ku_bsp_system_ddr4_0_0 || ORIG_REF_NAME==sis8300ku_bsp_system_ddr4_0_0} -quiet] -quiet

# IP: bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xlconstant_0_0/sis8300ku_bsp_system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sis8300ku_bsp_system_xlconstant_0_0 || ORIG_REF_NAME==sis8300ku_bsp_system_xlconstant_0_0} -quiet] -quiet

# XDC: bd/sis8300ku_bsp_system/sis8300ku_bsp_system_ooc.xdc
