== Register Descriptions

Most of the registers lengths gets configured through how many trigger outputs are configured for the Timing Module. (determined by a constant ``C_TRG_CNT``). This parameters currently gets fetched through appconfig. 

[cols="6,3,3,3,9"]
|===
|Name |Register Width |Number of Elements | RO/RW | Description

|ID
|32
|1
|RO
|LSB 8 bits shows number of output channels, next LSB 8 bits shows the number of external trigger channels that TIMING module is configured for

|VERSION
|32
|1
|RO
|Shows the git revision number

|ENABLE
|C_TRG_CNT
|1
|RW
|Enable the output of the particular trigger channel


|SOURCE_SEL
|8
|C_TRG_CNT
|RW
|Select the source for trigger generation.
*These numbers are application dependent.*
e.g. Single Cavity Regulation (7 Trigger channels with 8 external trigger sources, values are an integer!)

0 => Use Application Clock +
1 => Manual Trigger using WORD_MANUAL_TRG +
2 => Use Backplane Port 17-R +
3 => Use Backplane Port 17-T +
4 => Use Backplane Port 18-R +
5 => Use Backplane Port 18-T +
6 => Use Backplane Port 19-R +
7 => Use Backplane Port 19-T +
8 => Use Backplane Port 20-R +
9 => Use Backplane Port 20-T +
10 => Use Loopback Trigger Channel 0 +
11 => Use Loopback Trigger Channel 1 +
12 => Use Loopback Trigger Channel 2 +
13 => Use Loopback Trigger Channel 3 +
14 => Use Loopback Trigger Channel 4 +
15 => Use Loopback Trigger Channel 5 +
16 => Use Loopback Trigger Channel 6 +

|SYNC_SEL
|8
|C_TRG_CNT
|RW
|Select synchronization input for the particular trigger channel

0 => No synchronization (Free running) +
1 => Use Loopback Trigger Channel 0 +
2 => Use Loopback Trigger Channel 1 +
3 => Use Loopback Trigger Channel 2 +
4 => Use Loopback Trigger Channel 3 +
5 => Use Loopback Trigger Channel 4 +
6 => Use Loopback Trigger Channel 5 +
7 => Use Loopback Trigger Channel 6 +

|DIVIDER_VALUE
|32
|C_TRG_CNT
|RW
|Divider value for the particular trigger channel.
eg. If you want to divide by 2 write 1

|TRIGGER_CNT
|32
|C_TRG_CNT
|RO
|Counter for each generated trigger channel ( (!) It counts even if the output is disabled (!) )

|EXT_TRIGGER_CNT
|32
|C_TRG_CNT
|RO
|Counter for each external trigger coming into the Timing Module ( (!) Gets effected by WORD_DIVIDER_VALUE (!) )

|DELAY_ENABLE
|C_TRG_CNT
|1
|RW
|Enables the delayed version for that particular trigger channel

|DELAY_VALUE
|32
|C_TRG_CNT
|RW
|Delay value for that particular trigger channel


|MANUAL_TRG
|1
|C_TRG_CNT
|RW
|Manually triggering a particular trigger channel.
Writing 1 to a particular channel will trigger that channel once.
(If the divider is set to 0)


...
|===