# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_sys_reset_0_0/sis8300ku_bsp_system_sys_reset_0_0.xci
# IP: The module: 'sis8300ku_bsp_system_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_sys_reset_0_0/sis8300ku_bsp_system_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sis8300ku_bsp_system_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_sys_reset_0_0/sis8300ku_bsp_system_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sis8300ku_bsp_system_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_sys_reset_0_0/sis8300ku_bsp_system_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sis8300ku_bsp_system_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_sys_reset_0_0/sis8300ku_bsp_system_sys_reset_0_0.xci
# IP: The module: 'sis8300ku_bsp_system_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_sys_reset_0_0/sis8300ku_bsp_system_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sis8300ku_bsp_system_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_sys_reset_0_0/sis8300ku_bsp_system_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sis8300ku_bsp_system_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_sys_reset_0_0/sis8300ku_bsp_system_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sis8300ku_bsp_system_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
