# -------------------------------------------------------------------------------
# --          ____  _____________  __                                          --
# --         / __ \/ ____/ ___/\ \/ /                 _   _   _                --
# --        / / / / __/  \__ \  \  /                 / \ / \ / \               --
# --       / /_/ / /___ ___/ /  / /               = ( M | S | K )=             --
# --      /_____/_____//____/  /_/                   \_/ \_/ \_/               --
# --                                                                           --
# -------------------------------------------------------------------------------
# $Header$
# -------------------------------------------------------------------------------
#! @file   sis8300ku_adc_timing_121.xdc
#! @brief  constraint file for timing-related stuff for ADCs on SIS8300 KU
#! $Date: 2015-05-30 21:01:05 +0200 (Sat, 30 May 2015) $
# -------------------------------------------------------------------------------

# clocks generated by the Clock Distribution network
#   AD9510 clock distribution needs to be configured to output the same clock
#   on output 4 (towards the FPGA) as on outputs 5 and 6 (towards the ADCs)

# ADC data clocks

create_clock -period 8.205 -name CLK_DIV0_CLK05 [get_ports pi_ad9510_0_clk05_p]
create_clock -period 8.205 -name CLK_DIV1_CLK69 [get_ports pi_ad9510_1_clk69_p]
create_clock -period 8.205 -name CLK_ADC_DCO_0 [get_ports {pi_adc_dco_p[0]}]
create_clock -period 8.205 -name CLK_ADC_DCO_1 [get_ports {pi_adc_dco_p[1]}]
create_clock -period 8.205 -name CLK_ADC_DCO_2 [get_ports {pi_adc_dco_p[2]}]
create_clock -period 8.205 -name CLK_ADC_DCO_3 [get_ports {pi_adc_dco_p[3]}]
create_clock -period 8.205 -name CLK_ADC_DCO_4 [get_ports {pi_adc_dco_p[4]}]



