set_property SRC_FILE_INFO {cfile:/home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/sis8300ku_bsp_system_xdma_0_0/sis8300ku_bsp_system_xdma_0_0_in_context.xdc rfile:../../../dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_xdma_0_0/sis8300ku_bsp_system_xdma_0_0/sis8300ku_bsp_system_xdma_0_0_in_context.xdc id:1 order:EARLY scoped_inst:ins_sis8300ku_bsp_system_wrapper/sis8300ku_bsp_system_i/pcie/xdma_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_clocks.xdc rfile:../../../../../src/hw/bsp_sis8300ku/cstr/pin_assignments_clocks.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:/home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_adc.xdc rfile:../../../../../src/hw/bsp_sis8300ku/cstr/pin_assignments_adc.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:/home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_dac.xdc rfile:../../../../../src/hw/bsp_sis8300ku/cstr/pin_assignments_dac.xdc id:4} [current_design]
set_property SRC_FILE_INFO {cfile:/home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_rtm.xdc rfile:../../../../../src/hw/bsp_sis8300ku/cstr/pin_assignments_rtm.xdc id:5} [current_design]
set_property SRC_FILE_INFO {cfile:/home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_misc.xdc rfile:../../../../../src/hw/bsp_sis8300ku/cstr/pin_assignments_misc.xdc id:6} [current_design]
set_property SRC_FILE_INFO {cfile:/home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_pcie.xdc rfile:../../../../../src/hw/bsp_sis8300ku/cstr/pin_assignments_pcie.xdc id:7} [current_design]
set_property SRC_FILE_INFO {cfile:/home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/pin_assignments_ddr4.xdc rfile:../../../../../src/hw/bsp_sis8300ku/cstr/pin_assignments_ddr4.xdc id:8} [current_design]
set_property SRC_FILE_INFO {cfile:/home/kristiaanpelckmans/Downloads/dev4/fw/src/hw/bsp_sis8300ku/cstr/timing_clocks.xdc rfile:../../../../../src/hw/bsp_sis8300ku/cstr/timing_clocks.xdc id:9} [current_design]
current_instance ins_sis8300ku_bsp_system_wrapper/sis8300ku_bsp_system_i/pcie/xdma_0
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports sys_clk_gt] -edges {1 2 3} -edge_shift {0.000 -4.900 -9.800} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports sys_clk_gt] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_ports {}]
current_instance
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ18 [get_ports pi_125_clk_p]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK18 [get_ports pi_125_clk_n]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK12 [get_ports {po_mux_a_sel[0]}]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL13 [get_ports {po_mux_a_sel[1]}]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM12 [get_ports {po_mux_b_sel[0]}]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL12 [get_ports {po_mux_b_sel[1]}]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH11 [get_ports {po_mux_c_sel[0]}]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH13 [get_ports {po_mux_c_sel[1]}]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ13 [get_ports {po_mux_d_sel[0]}]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK13 [get_ports {po_mux_d_sel[1]}]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD11 [get_ports {po_mux_e_sel[0]}]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE13 [get_ports {po_mux_e_sel[1]}]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF13 [get_ports {po_mux_dac_sel[0]}]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE12 [get_ports {po_mux_dac_sel[1]}]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN11 [get_ports po_ad9510_sclk]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP13 [get_ports pio_ad9510_sdio]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL8 [get_ports {po_ad9510_cs_b[0]}]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ8 [get_ports {po_ad9510_cs_b[1]}]
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN12 [get_ports po_ad9510_function]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W25 [get_ports pi_ad9510_0_clk05_p]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y25 [get_ports pi_ad9510_0_clk05_n]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W23 [get_ports pi_ad9510_1_clk69_p]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W24 [get_ports pi_ad9510_1_clk69_n]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD30 [get_ports pi_dac_clk_fb_p]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD31 [get_ports pi_dac_clk_fb_n]
set_property src_info {type:XDC file:3 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V23 [get_ports {po_adc_cs_b[0]}]
set_property src_info {type:XDC file:3 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V22 [get_ports {po_adc_cs_b[1]}]
set_property src_info {type:XDC file:3 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W21 [get_ports {po_adc_cs_b[2]}]
set_property src_info {type:XDC file:3 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V21 [get_ports {po_adc_cs_b[3]}]
set_property src_info {type:XDC file:3 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC26 [get_ports {po_adc_cs_b[4]}]
set_property src_info {type:XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB24 [get_ports pio_adc_sdio]
set_property src_info {type:XDC file:3 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC24 [get_ports po_adc_sclk]
set_property src_info {type:XDC file:3 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC23 [get_ports po_adc_oe_n]
set_property src_info {type:XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y21 [get_ports po_adc_pdwn]
set_property src_info {type:XDC file:3 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y23 [get_ports {pi_adc_dco_p[0]}]
set_property src_info {type:XDC file:3 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA23 [get_ports {pi_adc_dco_n[0]}]
set_property src_info {type:XDC file:3 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M25 [get_ports {pi_adc_dco_p[1]}]
set_property src_info {type:XDC file:3 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M26 [get_ports {pi_adc_dco_n[1]}]
set_property src_info {type:XDC file:3 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E22 [get_ports {pi_adc_dco_p[2]}]
set_property src_info {type:XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E23 [get_ports {pi_adc_dco_n[2]}]
set_property src_info {type:XDC file:3 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F18 [get_ports {pi_adc_dco_p[3]}]
set_property src_info {type:XDC file:3 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F17 [get_ports {pi_adc_dco_n[3]}]
set_property src_info {type:XDC file:3 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H12 [get_ports {pi_adc_dco_p[4]}]
set_property src_info {type:XDC file:3 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G12 [get_ports {pi_adc_dco_n[4]}]
set_property src_info {type:XDC file:3 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA24 [get_ports {pi_adc_or_p[0]}]
set_property src_info {type:XDC file:3 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA25 [get_ports {pi_adc_or_n[0]}]
set_property src_info {type:XDC file:3 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N24 [get_ports {pi_adc_or_p[1]}]
set_property src_info {type:XDC file:3 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M24 [get_ports {pi_adc_or_n[1]}]
set_property src_info {type:XDC file:3 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E25 [get_ports {pi_adc_or_p[2]}]
set_property src_info {type:XDC file:3 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D25 [get_ports {pi_adc_or_n[2]}]
set_property src_info {type:XDC file:3 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17 [get_ports {pi_adc_or_p[3]}]
set_property src_info {type:XDC file:3 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G16 [get_ports {pi_adc_or_n[3]}]
set_property src_info {type:XDC file:3 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E16 [get_ports {pi_adc_or_p[4]}]
set_property src_info {type:XDC file:3 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D16 [get_ports {pi_adc_or_n[4]}]
set_property src_info {type:XDC file:3 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L22 [get_ports {pi_adc_data_p[0][0]}]
set_property src_info {type:XDC file:3 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K23 [get_ports {pi_adc_data_n[0][0]}]
set_property src_info {type:XDC file:3 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P24 [get_ports {pi_adc_data_p[0][1]}]
set_property src_info {type:XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P25 [get_ports {pi_adc_data_n[0][1]}]
set_property src_info {type:XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J24 [get_ports {pi_adc_data_p[0][2]}]
set_property src_info {type:XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J25 [get_ports {pi_adc_data_n[0][2]}]
set_property src_info {type:XDC file:3 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G25 [get_ports {pi_adc_data_p[0][3]}]
set_property src_info {type:XDC file:3 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G26 [get_ports {pi_adc_data_n[0][3]}]
set_property src_info {type:XDC file:3 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L25 [get_ports {pi_adc_data_p[0][4]}]
set_property src_info {type:XDC file:3 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K25 [get_ports {pi_adc_data_n[0][4]}]
set_property src_info {type:XDC file:3 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T24 [get_ports {pi_adc_data_p[0][5]}]
set_property src_info {type:XDC file:3 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T25 [get_ports {pi_adc_data_n[0][5]}]
set_property src_info {type:XDC file:3 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P26 [get_ports {pi_adc_data_p[0][6]}]
set_property src_info {type:XDC file:3 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N26 [get_ports {pi_adc_data_n[0][6]}]
set_property src_info {type:XDC file:3 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L23 [get_ports {pi_adc_data_p[0][7]}]
set_property src_info {type:XDC file:3 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L24 [get_ports {pi_adc_data_n[0][7]}]
set_property src_info {type:XDC file:3 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T27 [get_ports {pi_adc_data_p[0][8]}]
set_property src_info {type:XDC file:3 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R27 [get_ports {pi_adc_data_n[0][8]}]
set_property src_info {type:XDC file:3 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M27 [get_ports {pi_adc_data_p[0][9]}]
set_property src_info {type:XDC file:3 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L27 [get_ports {pi_adc_data_n[0][9]}]
set_property src_info {type:XDC file:3 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R25 [get_ports {pi_adc_data_p[0][10]}]
set_property src_info {type:XDC file:3 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R26 [get_ports {pi_adc_data_n[0][10]}]
set_property src_info {type:XDC file:3 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U24 [get_ports {pi_adc_data_p[0][11]}]
set_property src_info {type:XDC file:3 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U25 [get_ports {pi_adc_data_n[0][11]}]
set_property src_info {type:XDC file:3 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB25 [get_ports {pi_adc_data_p[0][12]}]
set_property src_info {type:XDC file:3 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB26 [get_ports {pi_adc_data_n[0][12]}]
set_property src_info {type:XDC file:3 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U21 [get_ports {pi_adc_data_p[0][13]}]
set_property src_info {type:XDC file:3 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U22 [get_ports {pi_adc_data_n[0][13]}]
set_property src_info {type:XDC file:3 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T22 [get_ports {pi_adc_data_p[0][14]}]
set_property src_info {type:XDC file:3 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T23 [get_ports {pi_adc_data_n[0][14]}]
set_property src_info {type:XDC file:3 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V26 [get_ports {pi_adc_data_p[0][15]}]
set_property src_info {type:XDC file:3 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W26 [get_ports {pi_adc_data_n[0][15]}]
set_property src_info {type:XDC file:3 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D28 [get_ports {pi_adc_data_p[1][0]}]
set_property src_info {type:XDC file:3 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C28 [get_ports {pi_adc_data_n[1][0]}]
set_property src_info {type:XDC file:3 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B29 [get_ports {pi_adc_data_p[1][1]}]
set_property src_info {type:XDC file:3 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A29 [get_ports {pi_adc_data_n[1][1]}]
set_property src_info {type:XDC file:3 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E28 [get_ports {pi_adc_data_p[1][2]}]
set_property src_info {type:XDC file:3 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D29 [get_ports {pi_adc_data_n[1][2]}]
set_property src_info {type:XDC file:3 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A27 [get_ports {pi_adc_data_p[1][3]}]
set_property src_info {type:XDC file:3 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A28 [get_ports {pi_adc_data_n[1][3]}]
set_property src_info {type:XDC file:3 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E26 [get_ports {pi_adc_data_p[1][4]}]
set_property src_info {type:XDC file:3 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D26 [get_ports {pi_adc_data_n[1][4]}]
set_property src_info {type:XDC file:3 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R21 [get_ports {pi_adc_data_p[1][5]}]
set_property src_info {type:XDC file:3 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R22 [get_ports {pi_adc_data_n[1][5]}]
set_property src_info {type:XDC file:3 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P20 [get_ports {pi_adc_data_p[1][6]}]
set_property src_info {type:XDC file:3 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P21 [get_ports {pi_adc_data_n[1][6]}]
set_property src_info {type:XDC file:3 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M20 [get_ports {pi_adc_data_p[1][7]}]
set_property src_info {type:XDC file:3 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L20 [get_ports {pi_adc_data_n[1][7]}]
set_property src_info {type:XDC file:3 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K20 [get_ports {pi_adc_data_p[1][8]}]
set_property src_info {type:XDC file:3 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K21 [get_ports {pi_adc_data_n[1][8]}]
set_property src_info {type:XDC file:3 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N21 [get_ports {pi_adc_data_p[1][9]}]
set_property src_info {type:XDC file:3 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M21 [get_ports {pi_adc_data_n[1][9]}]
set_property src_info {type:XDC file:3 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R23 [get_ports {pi_adc_data_p[1][10]}]
set_property src_info {type:XDC file:3 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P23 [get_ports {pi_adc_data_n[1][10]}]
set_property src_info {type:XDC file:3 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H27 [get_ports {pi_adc_data_p[1][11]}]
set_property src_info {type:XDC file:3 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G27 [get_ports {pi_adc_data_n[1][11]}]
set_property src_info {type:XDC file:3 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J23 [get_ports {pi_adc_data_p[1][12]}]
set_property src_info {type:XDC file:3 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H24 [get_ports {pi_adc_data_n[1][12]}]
set_property src_info {type:XDC file:3 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J26 [get_ports {pi_adc_data_p[1][13]}]
set_property src_info {type:XDC file:3 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H26 [get_ports {pi_adc_data_n[1][13]}]
set_property src_info {type:XDC file:3 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N22 [get_ports {pi_adc_data_p[1][14]}]
set_property src_info {type:XDC file:3 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M22 [get_ports {pi_adc_data_n[1][14]}]
set_property src_info {type:XDC file:3 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K26 [get_ports {pi_adc_data_p[1][15]}]
set_property src_info {type:XDC file:3 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K27 [get_ports {pi_adc_data_n[1][15]}]
set_property src_info {type:XDC file:3 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G20 [get_ports {pi_adc_data_p[2][0]}]
set_property src_info {type:XDC file:3 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F20 [get_ports {pi_adc_data_n[2][0]}]
set_property src_info {type:XDC file:3 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B20 [get_ports {pi_adc_data_p[2][1]}]
set_property src_info {type:XDC file:3 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A20 [get_ports {pi_adc_data_n[2][1]}]
set_property src_info {type:XDC file:3 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E20 [get_ports {pi_adc_data_p[2][2]}]
set_property src_info {type:XDC file:3 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E21 [get_ports {pi_adc_data_n[2][2]}]
set_property src_info {type:XDC file:3 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D20 [get_ports {pi_adc_data_p[2][3]}]
set_property src_info {type:XDC file:3 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D21 [get_ports {pi_adc_data_n[2][3]}]
set_property src_info {type:XDC file:3 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H21 [get_ports {pi_adc_data_p[2][4]}]
set_property src_info {type:XDC file:3 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G21 [get_ports {pi_adc_data_n[2][4]}]
set_property src_info {type:XDC file:3 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G24 [get_ports {pi_adc_data_p[2][5]}]
set_property src_info {type:XDC file:3 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F25 [get_ports {pi_adc_data_n[2][5]}]
set_property src_info {type:XDC file:3 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B21 [get_ports {pi_adc_data_p[2][6]}]
set_property src_info {type:XDC file:3 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B22 [get_ports {pi_adc_data_n[2][6]}]
set_property src_info {type:XDC file:3 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C21 [get_ports {pi_adc_data_p[2][7]}]
set_property src_info {type:XDC file:3 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C22 [get_ports {pi_adc_data_n[2][7]}]
set_property src_info {type:XDC file:3 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G22 [get_ports {pi_adc_data_p[2][8]}]
set_property src_info {type:XDC file:3 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F22 [get_ports {pi_adc_data_n[2][8]}]
set_property src_info {type:XDC file:3 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D24 [get_ports {pi_adc_data_p[2][9]}]
set_property src_info {type:XDC file:3 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C24 [get_ports {pi_adc_data_n[2][9]}]
set_property src_info {type:XDC file:3 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F23 [get_ports {pi_adc_data_p[2][10]}]
set_property src_info {type:XDC file:3 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F24 [get_ports {pi_adc_data_n[2][10]}]
set_property src_info {type:XDC file:3 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B25 [get_ports {pi_adc_data_p[2][11]}]
set_property src_info {type:XDC file:3 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A25 [get_ports {pi_adc_data_n[2][11]}]
set_property src_info {type:XDC file:3 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F27 [get_ports {pi_adc_data_p[2][12]}]
set_property src_info {type:XDC file:3 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E27 [get_ports {pi_adc_data_n[2][12]}]
set_property src_info {type:XDC file:3 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B24 [get_ports {pi_adc_data_p[2][13]}]
set_property src_info {type:XDC file:3 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A24 [get_ports {pi_adc_data_n[2][13]}]
set_property src_info {type:XDC file:3 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C26 [get_ports {pi_adc_data_p[2][14]}]
set_property src_info {type:XDC file:3 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B26 [get_ports {pi_adc_data_n[2][14]}]
set_property src_info {type:XDC file:3 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C27 [get_ports {pi_adc_data_p[2][15]}]
set_property src_info {type:XDC file:3 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B27 [get_ports {pi_adc_data_n[2][15]}]
set_property src_info {type:XDC file:3 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports {pi_adc_data_p[3][0]}]
set_property src_info {type:XDC file:3 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K15 [get_ports {pi_adc_data_n[3][0]}]
set_property src_info {type:XDC file:3 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L19 [get_ports {pi_adc_data_p[3][1]}]
set_property src_info {type:XDC file:3 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L18 [get_ports {pi_adc_data_n[3][1]}]
set_property src_info {type:XDC file:3 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B15 [get_ports {pi_adc_data_p[3][2]}]
set_property src_info {type:XDC file:3 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A15 [get_ports {pi_adc_data_n[3][2]}]
set_property src_info {type:XDC file:3 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E18 [get_ports {pi_adc_data_p[3][3]}]
set_property src_info {type:XDC file:3 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E17 [get_ports {pi_adc_data_n[3][3]}]
set_property src_info {type:XDC file:3 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J19 [get_ports {pi_adc_data_p[3][4]}]
set_property src_info {type:XDC file:3 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18 [get_ports {pi_adc_data_n[3][4]}]
set_property src_info {type:XDC file:3 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports {pi_adc_data_p[3][5]}]
set_property src_info {type:XDC file:3 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J14 [get_ports {pi_adc_data_n[3][5]}]
set_property src_info {type:XDC file:3 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports {pi_adc_data_p[3][6]}]
set_property src_info {type:XDC file:3 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H16 [get_ports {pi_adc_data_n[3][6]}]
set_property src_info {type:XDC file:3 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G19 [get_ports {pi_adc_data_p[3][7]}]
set_property src_info {type:XDC file:3 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F19 [get_ports {pi_adc_data_n[3][7]}]
set_property src_info {type:XDC file:3 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B17 [get_ports {pi_adc_data_p[3][8]}]
set_property src_info {type:XDC file:3 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B16 [get_ports {pi_adc_data_n[3][8]}]
set_property src_info {type:XDC file:3 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D19 [get_ports {pi_adc_data_p[3][9]}]
set_property src_info {type:XDC file:3 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports {pi_adc_data_n[3][9]}]
set_property src_info {type:XDC file:3 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15 [get_ports {pi_adc_data_p[3][10]}]
set_property src_info {type:XDC file:3 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14 [get_ports {pi_adc_data_n[3][10]}]
set_property src_info {type:XDC file:3 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K18 [get_ports {pi_adc_data_p[3][11]}]
set_property src_info {type:XDC file:3 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports {pi_adc_data_n[3][11]}]
set_property src_info {type:XDC file:3 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C19 [get_ports {pi_adc_data_p[3][12]}]
set_property src_info {type:XDC file:3 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B19 [get_ports {pi_adc_data_n[3][12]}]
set_property src_info {type:XDC file:3 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C18 [get_ports {pi_adc_data_p[3][13]}]
set_property src_info {type:XDC file:3 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C17 [get_ports {pi_adc_data_n[3][13]}]
set_property src_info {type:XDC file:3 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H19 [get_ports {pi_adc_data_p[3][14]}]
set_property src_info {type:XDC file:3 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports {pi_adc_data_n[3][14]}]
set_property src_info {type:XDC file:3 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A19 [get_ports {pi_adc_data_p[3][15]}]
set_property src_info {type:XDC file:3 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports {pi_adc_data_n[3][15]}]
set_property src_info {type:XDC file:3 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B9 [get_ports {pi_adc_data_p[4][0]}]
set_property src_info {type:XDC file:3 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A9 [get_ports {pi_adc_data_n[4][0]}]
set_property src_info {type:XDC file:3 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E10 [get_ports {pi_adc_data_p[4][1]}]
set_property src_info {type:XDC file:3 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D10 [get_ports {pi_adc_data_n[4][1]}]
set_property src_info {type:XDC file:3 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G10 [get_ports {pi_adc_data_p[4][2]}]
set_property src_info {type:XDC file:3 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F10 [get_ports {pi_adc_data_n[4][2]}]
set_property src_info {type:XDC file:3 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K10 [get_ports {pi_adc_data_p[4][3]}]
set_property src_info {type:XDC file:3 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J10 [get_ports {pi_adc_data_n[4][3]}]
set_property src_info {type:XDC file:3 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C11 [get_ports {pi_adc_data_p[4][4]}]
set_property src_info {type:XDC file:3 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B11 [get_ports {pi_adc_data_n[4][4]}]
set_property src_info {type:XDC file:3 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E11 [get_ports {pi_adc_data_p[4][5]}]
set_property src_info {type:XDC file:3 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D11 [get_ports {pi_adc_data_n[4][5]}]
set_property src_info {type:XDC file:3 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K11 [get_ports {pi_adc_data_p[4][6]}]
set_property src_info {type:XDC file:3 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J11 [get_ports {pi_adc_data_n[4][6]}]
set_property src_info {type:XDC file:3 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A13 [get_ports {pi_adc_data_p[4][7]}]
set_property src_info {type:XDC file:3 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A12 [get_ports {pi_adc_data_n[4][7]}]
set_property src_info {type:XDC file:3 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L13 [get_ports {pi_adc_data_p[4][8]}]
set_property src_info {type:XDC file:3 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K13 [get_ports {pi_adc_data_n[4][8]}]
set_property src_info {type:XDC file:3 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L12 [get_ports {pi_adc_data_p[4][9]}]
set_property src_info {type:XDC file:3 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K12 [get_ports {pi_adc_data_n[4][9]}]
set_property src_info {type:XDC file:3 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F13 [get_ports {pi_adc_data_p[4][10]}]
set_property src_info {type:XDC file:3 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13 [get_ports {pi_adc_data_n[4][10]}]
set_property src_info {type:XDC file:3 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D14 [get_ports {pi_adc_data_p[4][11]}]
set_property src_info {type:XDC file:3 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C14 [get_ports {pi_adc_data_n[4][11]}]
set_property src_info {type:XDC file:3 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F15 [get_ports {pi_adc_data_p[4][12]}]
set_property src_info {type:XDC file:3 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F14 [get_ports {pi_adc_data_n[4][12]}]
set_property src_info {type:XDC file:3 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E15 [get_ports {pi_adc_data_p[4][13]}]
set_property src_info {type:XDC file:3 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D15 [get_ports {pi_adc_data_n[4][13]}]
set_property src_info {type:XDC file:3 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K16 [get_ports {pi_adc_data_p[4][14]}]
set_property src_info {type:XDC file:3 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J16 [get_ports {pi_adc_data_n[4][14]}]
set_property src_info {type:XDC file:3 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B14 [get_ports {pi_adc_data_p[4][15]}]
set_property src_info {type:XDC file:3 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A14 [get_ports {pi_adc_data_n[4][15]}]
set_property src_info {type:XDC file:4 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC34 [get_ports {po_dac_data_p[0]}]
set_property src_info {type:XDC file:4 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD34 [get_ports {po_dac_data_n[0]}]
set_property src_info {type:XDC file:4 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE33 [get_ports {po_dac_data_p[1]}]
set_property src_info {type:XDC file:4 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF34 [get_ports {po_dac_data_n[1]}]
set_property src_info {type:XDC file:4 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA34 [get_ports {po_dac_data_p[2]}]
set_property src_info {type:XDC file:4 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB34 [get_ports {po_dac_data_n[2]}]
set_property src_info {type:XDC file:4 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE28 [get_ports {po_dac_data_p[3]}]
set_property src_info {type:XDC file:4 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF28 [get_ports {po_dac_data_n[3]}]
set_property src_info {type:XDC file:4 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE32 [get_ports {po_dac_data_p[4]}]
set_property src_info {type:XDC file:4 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF32 [get_ports {po_dac_data_n[4]}]
set_property src_info {type:XDC file:4 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC33 [get_ports {po_dac_data_p[5]}]
set_property src_info {type:XDC file:4 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD33 [get_ports {po_dac_data_n[5]}]
set_property src_info {type:XDC file:4 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB30 [get_ports {po_dac_data_p[6]}]
set_property src_info {type:XDC file:4 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB31 [get_ports {po_dac_data_n[6]}]
set_property src_info {type:XDC file:4 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y31 [get_ports {po_dac_data_p[7]}]
set_property src_info {type:XDC file:4 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y32 [get_ports {po_dac_data_n[7]}]
set_property src_info {type:XDC file:4 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA32 [get_ports {po_dac_data_p[8]}]
set_property src_info {type:XDC file:4 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB32 [get_ports {po_dac_data_n[8]}]
set_property src_info {type:XDC file:4 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V33 [get_ports {po_dac_data_p[9]}]
set_property src_info {type:XDC file:4 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W34 [get_ports {po_dac_data_n[9]}]
set_property src_info {type:XDC file:4 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W33 [get_ports {po_dac_data_p[10]}]
set_property src_info {type:XDC file:4 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y33 [get_ports {po_dac_data_n[10]}]
set_property src_info {type:XDC file:4 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC31 [get_ports {po_dac_data_p[11]}]
set_property src_info {type:XDC file:4 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC32 [get_ports {po_dac_data_n[11]}]
set_property src_info {type:XDC file:4 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U34 [get_ports {po_dac_data_p[12]}]
set_property src_info {type:XDC file:4 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V34 [get_ports {po_dac_data_n[12]}]
set_property src_info {type:XDC file:4 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA29 [get_ports {po_dac_data_p[13]}]
set_property src_info {type:XDC file:4 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB29 [get_ports {po_dac_data_n[13]}]
set_property src_info {type:XDC file:4 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD29 [get_ports {po_dac_data_p[14]}]
set_property src_info {type:XDC file:4 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE30 [get_ports {po_dac_data_n[14]}]
set_property src_info {type:XDC file:4 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V31 [get_ports {po_dac_data_p[15]}]
set_property src_info {type:XDC file:4 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W31 [get_ports {po_dac_data_n[15]}]
set_property src_info {type:XDC file:4 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W30 [get_ports po_dac_seliq_p]
set_property src_info {type:XDC file:4 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC28 [get_ports po_dac_clk_p]
set_property src_info {type:XDC file:4 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD28 [get_ports po_dac_clk_n]
set_property src_info {type:XDC file:4 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG29 [get_ports po_dac_pd]
set_property src_info {type:XDC file:4 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF29 [get_ports po_dac_torb]
set_property src_info {type:XDC file:5 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP11 [get_ports po_rtm_interlock_ena_n]
set_property src_info {type:XDC file:5 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP9 [get_ports {po_rtm_interlock[0]}]
set_property src_info {type:XDC file:5 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP10 [get_ports {po_rtm_interlock[1]}]
set_property src_info {type:XDC file:5 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B10 [get_ports {pio_rtm_io_p[0]}]
set_property src_info {type:XDC file:5 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A10 [get_ports {pio_rtm_io_n[0]}]
set_property src_info {type:XDC file:5 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G9 [get_ports {pio_rtm_io_p[1]}]
set_property src_info {type:XDC file:5 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F9 [get_ports {pio_rtm_io_n[1]}]
set_property src_info {type:XDC file:5 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D8 [get_ports {pio_rtm_io_p[2]}]
set_property src_info {type:XDC file:5 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C8 [get_ports {pio_rtm_io_n[2]}]
set_property src_info {type:XDC file:5 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L8 [get_ports {pio_rtm_io_p[3]}]
set_property src_info {type:XDC file:5 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K8 [get_ports {pio_rtm_io_n[3]}]
set_property src_info {type:XDC file:5 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C12 [get_ports {pio_rtm_io_p[4]}]
set_property src_info {type:XDC file:5 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B12 [get_ports {pio_rtm_io_n[4]}]
set_property src_info {type:XDC file:5 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H11 [get_ports {pio_rtm_io_p[5]}]
set_property src_info {type:XDC file:5 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G11 [get_ports {pio_rtm_io_n[5]}]
set_property src_info {type:XDC file:5 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D13 [get_ports {pio_rtm_io_p[6]}]
set_property src_info {type:XDC file:5 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C13 [get_ports {pio_rtm_io_n[6]}]
set_property src_info {type:XDC file:5 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J13 [get_ports {pio_rtm_io_p[7]}]
set_property src_info {type:XDC file:5 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H13 [get_ports {pio_rtm_io_n[7]}]
set_property src_info {type:XDC file:5 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J9 [get_ports {pio_rtm_io_p[8]}]
set_property src_info {type:XDC file:5 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H9 [get_ports {pio_rtm_io_n[8]}]
set_property src_info {type:XDC file:5 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J8 [get_ports {pio_rtm_io_p[9]}]
set_property src_info {type:XDC file:5 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H8 [get_ports {pio_rtm_io_n[9]}]
set_property src_info {type:XDC file:5 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F8 [get_ports {pio_rtm_io_p[10]}]
set_property src_info {type:XDC file:5 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E8 [get_ports {pio_rtm_io_n[10]}]
set_property src_info {type:XDC file:5 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D9 [get_ports {pio_rtm_io_p[11]}]
set_property src_info {type:XDC file:5 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C9 [get_ports {pio_rtm_io_n[11]}]
set_property src_info {type:XDC file:6 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM11 [get_ports po_led_serial_data]
set_property src_info {type:XDC file:6 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE11 [get_ports {po_mlvds[0]}]
set_property src_info {type:XDC file:6 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF12 [get_ports {po_mlvds[1]}]
set_property src_info {type:XDC file:6 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF8 [get_ports {po_mlvds[2]}]
set_property src_info {type:XDC file:6 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH12 [get_ports {po_mlvds[3]}]
set_property src_info {type:XDC file:6 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG12 [get_ports {po_mlvds[4]}]
set_property src_info {type:XDC file:6 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ9 [get_ports {po_mlvds[5]}]
set_property src_info {type:XDC file:6 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH9 [get_ports {po_mlvds[6]}]
set_property src_info {type:XDC file:6 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK8 [get_ports {po_mlvds[7]}]
set_property src_info {type:XDC file:6 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ11 [get_ports {pi_mlvds[0]}]
set_property src_info {type:XDC file:6 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK10 [get_ports {pi_mlvds[1]}]
set_property src_info {type:XDC file:6 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK11 [get_ports {pi_mlvds[2]}]
set_property src_info {type:XDC file:6 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL10 [get_ports {pi_mlvds[3]}]
set_property src_info {type:XDC file:6 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL9 [get_ports {pi_mlvds[4]}]
set_property src_info {type:XDC file:6 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM10 [get_ports {pi_mlvds[5]}]
set_property src_info {type:XDC file:6 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM9 [get_ports {pi_mlvds[6]}]
set_property src_info {type:XDC file:6 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN9 [get_ports {pi_mlvds[7]}]
set_property src_info {type:XDC file:6 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD9 [get_ports {po_mlvds_oe[0]}]
set_property src_info {type:XDC file:6 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD10 [get_ports {po_mlvds_oe[1]}]
set_property src_info {type:XDC file:6 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE8 [get_ports {po_mlvds_oe[2]}]
set_property src_info {type:XDC file:6 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD8 [get_ports {po_mlvds_oe[3]}]
set_property src_info {type:XDC file:6 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ10 [get_ports {po_mlvds_oe[4]}]
set_property src_info {type:XDC file:6 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH8 [get_ports {po_mlvds_oe[5]}]
set_property src_info {type:XDC file:6 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN8 [get_ports {po_mlvds_oe[6]}]
set_property src_info {type:XDC file:6 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP8 [get_ports {po_mlvds_oe[7]}]
set_property src_info {type:XDC file:6 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W28 [get_ports {po_fp_data_p[0]}]
set_property src_info {type:XDC file:6 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y28 [get_ports {po_fp_data_n[0]}]
set_property src_info {type:XDC file:6 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD25 [get_ports {po_fp_data_p[1]}]
set_property src_info {type:XDC file:6 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD26 [get_ports {po_fp_data_n[1]}]
set_property src_info {type:XDC file:6 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U26 [get_ports {po_fp_data_p[2]}]
set_property src_info {type:XDC file:6 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U27 [get_ports {po_fp_data_n[2]}]
set_property src_info {type:XDC file:6 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V29 [get_ports {pi_fp_data_p[0]}]
set_property src_info {type:XDC file:6 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W29 [get_ports {pi_fp_data_n[0]}]
set_property src_info {type:XDC file:6 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA27 [get_ports {pi_fp_data_p[1]}]
set_property src_info {type:XDC file:6 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB27 [get_ports {pi_fp_data_n[1]}]
set_property src_info {type:XDC file:6 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V27 [get_ports {pi_fp_data_p[2]}]
set_property src_info {type:XDC file:6 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V28 [get_ports {pi_fp_data_n[2]}]
set_property src_info {type:XDC file:7 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N23 [get_ports pi_pcie_rst_n]
set_property src_info {type:XDC file:7 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P5 [get_ports pi_pcie_clk_n]
set_property src_info {type:XDC file:7 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P6 [get_ports pi_pcie_clk_p]
set_property src_info {type:XDC file:8 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF14 [get_ports {po_ddr4_adr[16]}]
set_property src_info {type:XDC file:8 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG14 [get_ports {po_ddr4_adr[15]}]
set_property src_info {type:XDC file:8 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE18 [get_ports {po_ddr4_adr[14]}]
set_property src_info {type:XDC file:8 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD15 [get_ports {po_ddr4_adr[13]}]
set_property src_info {type:XDC file:8 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG15 [get_ports {po_ddr4_adr[12]}]
set_property src_info {type:XDC file:8 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH14 [get_ports {po_ddr4_adr[11]}]
set_property src_info {type:XDC file:8 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF15 [get_ports {po_ddr4_adr[10]}]
set_property src_info {type:XDC file:8 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF18 [get_ports {po_ddr4_adr[9]}]
set_property src_info {type:XDC file:8 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD14 [get_ports {po_ddr4_adr[8]}]
set_property src_info {type:XDC file:8 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ14 [get_ports {po_ddr4_adr[7]}]
set_property src_info {type:XDC file:8 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE17 [get_ports {po_ddr4_adr[6]}]
set_property src_info {type:XDC file:8 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL15 [get_ports {po_ddr4_adr[5]}]
set_property src_info {type:XDC file:8 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG16 [get_ports {po_ddr4_adr[4]}]
set_property src_info {type:XDC file:8 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF17 [get_ports {po_ddr4_adr[3]}]
set_property src_info {type:XDC file:8 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK17 [get_ports {po_ddr4_adr[2]}]
set_property src_info {type:XDC file:8 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL17 [get_ports {po_ddr4_adr[1]}]
set_property src_info {type:XDC file:8 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH17 [get_ports {po_ddr4_adr[0]}]
set_property src_info {type:XDC file:8 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ16 [get_ports {po_ddr4_ba[1]}]
set_property src_info {type:XDC file:8 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD18 [get_ports {po_ddr4_ba[0]}]
set_property src_info {type:XDC file:8 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG19 [get_ports {po_ddr4_cke[0]}]
set_property src_info {type:XDC file:8 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG17 [get_ports {po_ddr4_cs_n[0]}]
set_property src_info {type:XDC file:8 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL32 [get_ports {pio_ddr4_dm_dbi_n[7]}]
set_property src_info {type:XDC file:8 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ29 [get_ports {pio_ddr4_dm_dbi_n[6]}]
set_property src_info {type:XDC file:8 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN26 [get_ports {pio_ddr4_dm_dbi_n[5]}]
set_property src_info {type:XDC file:8 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH26 [get_ports {pio_ddr4_dm_dbi_n[4]}]
set_property src_info {type:XDC file:8 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM21 [get_ports {pio_ddr4_dm_dbi_n[3]}]
set_property src_info {type:XDC file:8 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ21 [get_ports {pio_ddr4_dm_dbi_n[2]}]
set_property src_info {type:XDC file:8 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE25 [get_ports {pio_ddr4_dm_dbi_n[1]}]
set_property src_info {type:XDC file:8 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD21 [get_ports {pio_ddr4_dm_dbi_n[0]}]
set_property src_info {type:XDC file:8 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP31 [get_ports {pio_ddr4_dq[63]}]
set_property src_info {type:XDC file:8 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL34 [get_ports {pio_ddr4_dq[62]}]
set_property src_info {type:XDC file:8 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN31 [get_ports {pio_ddr4_dq[61]}]
set_property src_info {type:XDC file:8 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN32 [get_ports {pio_ddr4_dq[60]}]
set_property src_info {type:XDC file:8 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP33 [get_ports {pio_ddr4_dq[59]}]
set_property src_info {type:XDC file:8 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM34 [get_ports {pio_ddr4_dq[58]}]
set_property src_info {type:XDC file:8 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM32 [get_ports {pio_ddr4_dq[57]}]
set_property src_info {type:XDC file:8 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN33 [get_ports {pio_ddr4_dq[56]}]
set_property src_info {type:XDC file:8 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK32 [get_ports {pio_ddr4_dq[55]}]
set_property src_info {type:XDC file:8 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH34 [get_ports {pio_ddr4_dq[54]}]
set_property src_info {type:XDC file:8 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ30 [get_ports {pio_ddr4_dq[53]}]
set_property src_info {type:XDC file:8 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ31 [get_ports {pio_ddr4_dq[52]}]
set_property src_info {type:XDC file:8 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK31 [get_ports {pio_ddr4_dq[51]}]
set_property src_info {type:XDC file:8 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ34 [get_ports {pio_ddr4_dq[50]}]
set_property src_info {type:XDC file:8 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH32 [get_ports {pio_ddr4_dq[49]}]
set_property src_info {type:XDC file:8 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH31 [get_ports {pio_ddr4_dq[48]}]
set_property src_info {type:XDC file:8 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN27 [get_ports {pio_ddr4_dq[47]}]
set_property src_info {type:XDC file:8 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM29 [get_ports {pio_ddr4_dq[46]}]
set_property src_info {type:XDC file:8 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP28 [get_ports {pio_ddr4_dq[45]}]
set_property src_info {type:XDC file:8 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL30 [get_ports {pio_ddr4_dq[44]}]
set_property src_info {type:XDC file:8 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP29 [get_ports {pio_ddr4_dq[43]}]
set_property src_info {type:XDC file:8 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM30 [get_ports {pio_ddr4_dq[42]}]
set_property src_info {type:XDC file:8 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN28 [get_ports {pio_ddr4_dq[41]}]
set_property src_info {type:XDC file:8 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL29 [get_ports {pio_ddr4_dq[40]}]
set_property src_info {type:XDC file:8 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH28 [get_ports {pio_ddr4_dq[39]}]
set_property src_info {type:XDC file:8 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK28 [get_ports {pio_ddr4_dq[38]}]
set_property src_info {type:XDC file:8 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH27 [get_ports {pio_ddr4_dq[37]}]
set_property src_info {type:XDC file:8 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM27 [get_ports {pio_ddr4_dq[36]}]
set_property src_info {type:XDC file:8 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ28 [get_ports {pio_ddr4_dq[35]}]
set_property src_info {type:XDC file:8 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK27 [get_ports {pio_ddr4_dq[34]}]
set_property src_info {type:XDC file:8 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM26 [get_ports {pio_ddr4_dq[33]}]
set_property src_info {type:XDC file:8 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK26 [get_ports {pio_ddr4_dq[32]}]
set_property src_info {type:XDC file:8 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN23 [get_ports {pio_ddr4_dq[31]}]
set_property src_info {type:XDC file:8 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP24 [get_ports {pio_ddr4_dq[30]}]
set_property src_info {type:XDC file:8 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM24 [get_ports {pio_ddr4_dq[29]}]
set_property src_info {type:XDC file:8 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP25 [get_ports {pio_ddr4_dq[28]}]
set_property src_info {type:XDC file:8 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP23 [get_ports {pio_ddr4_dq[27]}]
set_property src_info {type:XDC file:8 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN24 [get_ports {pio_ddr4_dq[26]}]
set_property src_info {type:XDC file:8 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM22 [get_ports {pio_ddr4_dq[25]}]
set_property src_info {type:XDC file:8 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN22 [get_ports {pio_ddr4_dq[24]}]
set_property src_info {type:XDC file:8 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL24 [get_ports {pio_ddr4_dq[23]}]
set_property src_info {type:XDC file:8 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK22 [get_ports {pio_ddr4_dq[22]}]
set_property src_info {type:XDC file:8 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK23 [get_ports {pio_ddr4_dq[21]}]
set_property src_info {type:XDC file:8 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM20 [get_ports {pio_ddr4_dq[20]}]
set_property src_info {type:XDC file:8 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL23 [get_ports {pio_ddr4_dq[19]}]
set_property src_info {type:XDC file:8 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL22 [get_ports {pio_ddr4_dq[18]}]
set_property src_info {type:XDC file:8 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL25 [get_ports {pio_ddr4_dq[17]}]
set_property src_info {type:XDC file:8 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL20 [get_ports {pio_ddr4_dq[16]}]
set_property src_info {type:XDC file:8 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ23 [get_ports {pio_ddr4_dq[15]}]
set_property src_info {type:XDC file:8 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG24 [get_ports {pio_ddr4_dq[14]}]
set_property src_info {type:XDC file:8 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF24 [get_ports {pio_ddr4_dq[13]}]
set_property src_info {type:XDC file:8 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG25 [get_ports {pio_ddr4_dq[12]}]
set_property src_info {type:XDC file:8 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF23 [get_ports {pio_ddr4_dq[11]}]
set_property src_info {type:XDC file:8 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ24 [get_ports {pio_ddr4_dq[10]}]
set_property src_info {type:XDC file:8 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH22 [get_ports {pio_ddr4_dq[9]}]
set_property src_info {type:XDC file:8 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH23 [get_ports {pio_ddr4_dq[8]}]
set_property src_info {type:XDC file:8 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE20 [get_ports {pio_ddr4_dq[7]}]
set_property src_info {type:XDC file:8 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE23 [get_ports {pio_ddr4_dq[6]}]
set_property src_info {type:XDC file:8 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD20 [get_ports {pio_ddr4_dq[5]}]
set_property src_info {type:XDC file:8 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG22 [get_ports {pio_ddr4_dq[4]}]
set_property src_info {type:XDC file:8 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF20 [get_ports {pio_ddr4_dq[3]}]
set_property src_info {type:XDC file:8 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF22 [get_ports {pio_ddr4_dq[2]}]
set_property src_info {type:XDC file:8 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG20 [get_ports {pio_ddr4_dq[1]}]
set_property src_info {type:XDC file:8 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE22 [get_ports {pio_ddr4_dq[0]}]
set_property src_info {type:XDC file:8 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP34 [get_ports {pio_ddr4_dqs_c[7]}]
set_property src_info {type:XDC file:8 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ33 [get_ports {pio_ddr4_dqs_c[6]}]
set_property src_info {type:XDC file:8 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP30 [get_ports {pio_ddr4_dqs_c[5]}]
set_property src_info {type:XDC file:8 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL28 [get_ports {pio_ddr4_dqs_c[4]}]
set_property src_info {type:XDC file:8 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP21 [get_ports {pio_ddr4_dqs_c[3]}]
set_property src_info {type:XDC file:8 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK20 [get_ports {pio_ddr4_dqs_c[2]}]
set_property src_info {type:XDC file:8 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ25 [get_ports {pio_ddr4_dqs_c[1]}]
set_property src_info {type:XDC file:8 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH21 [get_ports {pio_ddr4_dqs_c[0]}]
set_property src_info {type:XDC file:8 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH19 [get_ports {po_ddr4_odt[0]}]
set_property src_info {type:XDC file:8 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD19 [get_ports {po_ddr4_bg[0]}]
set_property src_info {type:XDC file:8 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD16 [get_ports po_ddr4_rst_n]
set_property src_info {type:XDC file:8 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH18 [get_ports po_ddr4_act_n]
set_property src_info {type:XDC file:8 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE16 [get_ports {po_ddr4_ck_t[0]}]
set_property src_info {type:XDC file:8 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE15 [get_ports {po_ddr4_ck_c[0]}]
set_property src_info {type:XDC file:9 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins ins_sis8300ku_bsp_logic_top/blk_clock.ins_mmcm_app/inst_mmcm_adv/CLKINSEL]
set_property src_info {type:XDC file:9 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:9 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:9 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:9 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
