# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/sis8300ku_bsp_system_axi_interconnect_ddr_0.xci
# IP: The module: 'sis8300ku_bsp_system_axi_interconnect_ddr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/bd_9e20.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_0/bd_9e20_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_1/bd_9e20_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_2/bd_9e20_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_3/bd_9e20_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_4/bd_9e20_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_5/bd_9e20_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_6/bd_9e20_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_7/bd_9e20_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_8/bd_9e20_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_9/bd_9e20_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_10/bd_9e20_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_11/bd_9e20_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_12/bd_9e20_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_13/bd_9e20_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_14/bd_9e20_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_15/bd_9e20_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_16/bd_9e20_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_17/bd_9e20_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_18/bd_9e20_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_19/bd_9e20_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_20/bd_9e20_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_21/bd_9e20_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_22/bd_9e20_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_23/bd_9e20_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_24/bd_9e20_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_25/bd_9e20_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_26/bd_9e20_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_27/bd_9e20_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_28/bd_9e20_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_29/bd_9e20_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_30/bd_9e20_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_31/bd_9e20_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_32/bd_9e20_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_33/bd_9e20_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_1/bd_9e20_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_1/bd_9e20_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_2/bd_9e20_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_2/bd_9e20_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_3/bd_9e20_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_3/bd_9e20_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_4/bd_9e20_arsw_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_5/bd_9e20_rsw_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_6/bd_9e20_awsw_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_7/bd_9e20_wsw_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_8/bd_9e20_bsw_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_12/bd_9e20_s00a2s_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_13/bd_9e20_sarn_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_14/bd_9e20_srn_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_15/bd_9e20_sawn_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_16/bd_9e20_swn_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_17/bd_9e20_sbn_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_21/bd_9e20_s01a2s_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_22/bd_9e20_sarn_1_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_23/bd_9e20_srn_1_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_24/bd_9e20_sawn_1_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_25/bd_9e20_swn_1_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_26/bd_9e20_sbn_1_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_27/bd_9e20_m00s2a_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_28/bd_9e20_m00arn_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_29/bd_9e20_m00rn_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_30/bd_9e20_m00awn_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_31/bd_9e20_m00wn_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_32/bd_9e20_m00bn_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sis8300ku_bsp_system_axi_interconnect_ddr_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/sis8300ku_bsp_system_axi_interconnect_ddr_0.xci
# IP: The module: 'sis8300ku_bsp_system_axi_interconnect_ddr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/bd_9e20.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_0/bd_9e20_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_1/bd_9e20_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_2/bd_9e20_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_3/bd_9e20_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_4/bd_9e20_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_5/bd_9e20_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_6/bd_9e20_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_7/bd_9e20_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_8/bd_9e20_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_9/bd_9e20_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_10/bd_9e20_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_11/bd_9e20_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_12/bd_9e20_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_13/bd_9e20_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_14/bd_9e20_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_15/bd_9e20_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_16/bd_9e20_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_17/bd_9e20_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_18/bd_9e20_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_19/bd_9e20_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_20/bd_9e20_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_21/bd_9e20_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_22/bd_9e20_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_23/bd_9e20_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_24/bd_9e20_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_25/bd_9e20_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_26/bd_9e20_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_27/bd_9e20_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_28/bd_9e20_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_29/bd_9e20_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_30/bd_9e20_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_31/bd_9e20_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_32/bd_9e20_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_33/bd_9e20_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_1/bd_9e20_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_1/bd_9e20_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_2/bd_9e20_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_2/bd_9e20_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_3/bd_9e20_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_3/bd_9e20_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_4/bd_9e20_arsw_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_5/bd_9e20_rsw_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_6/bd_9e20_awsw_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_7/bd_9e20_wsw_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_8/bd_9e20_bsw_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_12/bd_9e20_s00a2s_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_13/bd_9e20_sarn_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_14/bd_9e20_srn_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_15/bd_9e20_sawn_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_16/bd_9e20_swn_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_17/bd_9e20_sbn_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_21/bd_9e20_s01a2s_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_22/bd_9e20_sarn_1_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_23/bd_9e20_srn_1_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_24/bd_9e20_sawn_1_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_25/bd_9e20_swn_1_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_26/bd_9e20_sbn_1_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_27/bd_9e20_m00s2a_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_28/bd_9e20_m00arn_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_29/bd_9e20_m00rn_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_30/bd_9e20_m00awn_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_31/bd_9e20_m00wn_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/bd_0/ip/ip_32/bd_9e20_m00bn_0_ooc.xdc

# XDC: /home/kristiaanpelckmans/Downloads/dev4/fw/prj/dev4_dwc8vm1/dev4_dwc8vm1.srcs/sources_1/bd/sis8300ku_bsp_system/ip/sis8300ku_bsp_system_axi_interconnect_ddr_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sis8300ku_bsp_system_axi_interconnect_ddr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
